const CONSTANSTS = {
    THEMES: {
        DARK: 'DARK',
        LIGHT: 'LIGHT'
    },
    ACTIONTYPES: {
        RESET_FORM: 'RESET_FORM',
        AUTOCOMPLETE_REQUEST: 'AUTOCOMPLETE_REQUEST',
        AUTOCOMPLETE_SUCCESS: 'AUTOCOMPLETE_SUCCESS',
        AUTOCOMPLETE_ERROR: 'AUTOCOMPLETE_ERROR'
    }
}

// enum


export default CONSTANSTS